In [1]:
pip install Faker

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting Faker
  Downloading Faker-13.12.1-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 13.9 MB/s
Requirement already satisfied: typing-extensions>=3.10.0.2 in /usr/local/lib/python3.7/dist-packages (from Faker) (4.2.0)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.7/dist-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.4->Faker) (1.15.0)
Installing collected packages: Faker
Successfully installed Faker-13.12.1

In [2]:
pip install nameparser

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting nameparser
  Downloading nameparser-1.1.1-py2.py3-none-any.whl (24 kB)
Installing collected packages: nameparser
Successfully installed nameparser-1.1.1

In [3]:
from nameparser import HumanName

In [4]:
import pandas as pd
import random
from faker import Faker
from random import randrange
from datetime import datetime

In [13]:
import faker


nr_of_customers = 1000

fake = Faker('de_DE')

customers = []

for customers_id in range(nr_of_customers):

    # Create start and end date 
    start_date = fake.date()
    end_date = fake.date()
    start_time = fake.time()
    end_time = fake.time()
    time_list = []
    for i in range(10):
     if start_time > end_time:
      start_time = fake.time()
     else:
      time_list.append(str(start_time))
      break
    time_string = ''.join(map(str, time_list))
    

    watering_time = fake.time()

    Plants = fake.numerify()

    #create customer's name
    Name = fake.name()

    
    status = fake.boolean()

    if status is True:
      status='Paid'
    else:
      status='Not Paid'

    #create place name

    Place_name = fake.city_name()

    seed_id = fake.iana_id

    #plant type
    street_address = fake.city_suffix()

    # Create gender
    #gender = random.choice(["M", "F"]))

    #Create city
    city = fake.city()

    #create product ID in 8-digit barcode
    Place_ID = fake.ean(length=8)
    
    #create amount spent
    Zip_code = fake.postcode()
    #(right_digits=2, positive=True, min_value=1, max_value=100)

    #createdseed
  
    seedid = fake.numerify()
    category1 = ['nucleus seed', 'breeder seed', 'foundation seed', 'certified seed']
    category = random.choice(category1)
    seeds1 = ['FlaxSeeds', 'Chia Seeds', 'Rajgira Seeds', 'Sunflower Seeds', 'Pumpkin Seeds', 'Basil Seeds', 'Hemp Seeds', 'Pomegranate Seeds']
    seeds = random.choice(seeds1)
    priceperseed = fake.pyfloat(positive=True, right_digits=2, left_digits=2)


    #factors
    season1 = ['Summer', 'Winter', 'Spring', 'Autumn']
    season = random.choice(season1)

    holidays = fake.day_of_week()
    specialevent = fake.boolean()

    if specialevent is True:
      specialevent='Premium'
    else:
      specialevent='Standard'
    historicw1 = ['Sunny', 'Rainy', 'Windy', 'Hot', 'Cloudy', 'Stormy', 'Cold']
    historicweather = random.choice(historicw1)
    competitorprices = fake.pyfloat(positive=True, right_digits=2, left_digits=2)


    #purchaseplant
    plantid = fake.numerify()
    farmerid = fake.numerify()
    pricepayed = fake.pyfloat(positive=True, right_digits=2, left_digits=2)
    timestamp = fake.date_time()
    plantstatus = fake.boolean()

    if plantstatus is True:
      plantstatus='Active'
    else:
      plantstatus='Cancel'
    pickuptimestamp = fake.date_time()
    partnerid = fake.numerify()
    marketdata = fake.numerify()
    #farmer
    farmerid = fake.numerify()
    firstname1 = Name
    parsed_name1 = HumanName(firstname1)
    firstname = parsed_name1.first
    lastname1 = Name
    parsed_name = HumanName(lastname1)
    lastname = parsed_name.last
    birthdate = fake.date()
    gender = random.choice(["M", "F"])









    customers.append([Place_ID, Place_name, Name, start_date, end_date, time_string, end_time, watering_time, Plants, status, street_address, Zip_code, city, seedid , category, seeds, priceperseed, season, holidays, specialevent, historicweather, competitorprices, plantid, farmerid, pricepayed, timestamp, plantstatus, pickuptimestamp, partnerid, marketdata,  farmerid, firstname, lastname, birthdate, gender])


customers_df = pd.DataFrame(customers, columns=['Place_id', 'Place_name', 'Name', 'start_date', 'end_date', 'start_time', 'end_time', 'watering_time', 'Plants', 'status', 'street_address', 'Zip_code', 'city', 'seedid' , 'category', 'seeds',  'priceperseed', 'season', 'holidays', 'specialevent', 'historicweather', 'competitorprices', 'plantid', 'farmerid', 'pricepayed', 'timestamp', 'plantstatus', 'pickuptimestamp', 'partnerid', 'marketdata',  'farmerid', 'firstname', 'lastname', 'birthdate', 'gender']) 
                
pd.pandas.set_option('display.max_columns', None)
customers_df.head(10)

,Place_id,Place_name,Name,start_date,end_date,start_time,end_time,watering_time,Plants,status,street_address,Zip_code,city,seedid,category,seeds,priceperseed,season,holidays,specialevent,historicweather,competitorprices,plantid,farmerid,pricepayed,timestamp,plantstatus,pickuptimestamp,partnerid,marketdata,farmerid,firstname,lastname,birthdate,gender
0,45718946,Ludwigslust,Willy Kramer,2000-01-13,1986-01-15,03:11:12,09:15:19,16:43:50,814,Paid,Ville,40826,Schweinfurt,374,breeder seed,Basil Seeds,77.67,Autumn,Samstag,Premium,Sunny,67.26,085,868,37.65,2007-02-02 01:37:24,Cancel,2001-12-28 22:15:13,997,620,868,Willy,Kramer,1998-04-25,F
1,56708462,Göppingen,Delia Fiebig-Hahn,1987-08-04,1971-05-09,02:38:45,16:34:12,20:48:42,002,Not Paid,Ville,49852,Bad Langensalza,843,breeder seed,Basil Seeds,56.46,Winter,Montag,Standard,Sunny,59.76,492,391,21.70,2013-01-28 05:05:42,Cancel,2021-10-18 14:10:00,404,991,391,Delia,Fiebig-Hahn,1994-07-06,F
2,15972835,Moers,Frank-Peter Losekann-Hölzenbecher,1978-12-30,2016-02-09,15:00:44,16:51:47,00:10:11,112,Paid,Ville,73375,Miltenberg,864,breeder seed,Pomegranate Seeds,94.50,Summer,Samstag,Premium,Cold,0.29,532,239,87.17,2020-02-25 01:09:12,Cancel,2016-06-03 19:00:12,556,657,239,Frank-Peter,Losekann-Hölzenbecher,2002-08-26,F
3,46139207,Hoyerswerda,Reimund Kambs,2014-07-06,1971-03-11,08:55:28,23:34:23,04:14:34,755,Paid,Ville,99831,Jessen,419,nucleus seed,Pomegranate Seeds,17.79,Winter,Samstag,Standard,Cold,1.44,878,068,15.47,1995-06-08 00:41:05,Cancel,1993-08-30 12:00:26,659,558,068,Reimund,Kambs,1997-05-18,F
4,98317332,Feuchtwangen,Janett Ziegert-Fiebig,2014-12-26,1977-07-31,14:43:29,17:41:29,11:48:29,392,Not Paid,Ville,75022,Konstanz,359,certified seed,Chia Seeds,51.51,Autumn,Mittwoch,Premium,Cloudy,23.95,821,699,85.29,1980-02-23 09:25:29,Cancel,1983-05-27 11:06:19,793,582,699,Janett,Ziegert-Fiebig,1977-08-24,F
5,49720846,Nördlingen,Renato Klemt-Schleich,2008-06-07,2007-09-10,09:20:54,15:04:11,15:34:38,618,Paid,Ville,32093,Königs Wusterhausen,889,nucleus seed,Chia Seeds,21.83,Autumn,Dienstag,Standard,Stormy,57.99,210,946,18.38,2015-08-08 04:12:38,Cancel,1992-06-29 01:28:18,373,854,946,Renato,Klemt-Schleich,2014-11-18,F
6,50819157,Güstrow,Eitel Ehlert,2011-02-15,1972-06-01,12:29:13,16:13:47,09:31:28,271,Paid,Ville,26316,Darmstadt,623,certified seed,Basil Seeds,73.75,Autumn,Donnerstag,Standard,Sunny,56.37,567,726,67.59,1998-09-10 03:10:00,Active,1989-01-29 18:10:52,152,121,726,Eitel,Ehlert,1974-10-23,M
7,92520257,Forchheim,Marc Otto,1982-03-19,2016-10-21,04:34:20,14:05:38,16:43:32,228,Paid,Ville,37433,Witzenhausen,844,nucleus seed,Sunflower Seeds,88.96,Spring,Donnerstag,Premium,Rainy,25.44,620,707,96.10,2001-10-12 21:52:03,Cancel,1985-09-21 23:48:38,879,462,707,Marc,Otto,2015-01-12,F
8,59019633,Moers,Tino Zorbach,1982-01-05,2004-03-09,20:17:03,23:29:11,19:49:36,974,Not Paid,Ville,43785,Sternberg,468,foundation seed,Chia Seeds,23.29,Autumn,Samstag,Standard,Hot,69.95,482,916,67.85,2010-03-06 19:01:46,Active,1972-07-21 07:18:46,785,462,916,Tino,Zorbach,2014-12-11,F
9,41350997,Luckenwalde,Jörgen Trapp,1973-08-07,1994-02-15,03:35:17,08:37:37,05:21:39,583,Paid,Ville,80455,Bad Brückenau,817,foundation seed,Hemp Seeds,96.62,Summer,Sonntag,Premium,Cold,22.43,859,750,92.33,1975-10-30 11:05:10,Active,1971-02-22 07:24:19,847,101,750,Jörgen,Trapp,2015-09-18,F

In [12]:
time_string = ''.join(map(str, time_list))
print(time_string)

08:10:37

In [14]:
customers_df.to_csv(r'/content/data.csv', index=False)